# Generated by Django 5.2.5 on 2025-08-18 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoflix_app', '0002_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='has_1080p',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='has_480p',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='has_720p',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='is_processing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='videos/previews/'),
        ),
        migrations.AddField(
            model_name='video',
            name='processing_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnail_image',
            field=models.ImageField(blank=True, null=True, upload_to='videos/thumbnails/'),
        ),
        migrations.AddField(
            model_name='video',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/originals/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
